"""Add MCP models: mcp_servers, mcp_server_configs, mcp_tool_executions, mcp_server_registry

Revision ID: 71c3dad7290a
Revises: 583707ecf3d3
Create Date: 2025-11-21 23:25:06.094160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c3dad7290a'
down_revision: Union[str, None] = '583707ecf3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_server_registry',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('server_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('install_command', sa.Text(), nullable=True),
    sa.Column('configuration_schema', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('repository_url', sa.String(length=1000), nullable=True),
    sa.Column('documentation_url', sa.String(length=1000), nullable=True),
    sa.Column('homepage_url', sa.String(length=1000), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('star_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('tool_definitions', sa.JSON(), nullable=True),
    sa.Column('resource_definitions', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_registry_category', 'mcp_server_registry', ['category'], unique=False)
    op.create_index('idx_registry_featured', 'mcp_server_registry', ['is_featured'], unique=False)
    op.create_index('idx_registry_status', 'mcp_server_registry', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_server_registry_category'), 'mcp_server_registry', ['category'], unique=False)
    op.create_index(op.f('ix_mcp_server_registry_name'), 'mcp_server_registry', ['name'], unique=True)
    op.create_index(op.f('ix_mcp_server_registry_slug'), 'mcp_server_registry', ['slug'], unique=True)
    op.create_index(op.f('ix_mcp_server_registry_status'), 'mcp_server_registry', ['status'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('server_type', sa.String(length=50), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('prompts', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('env_vars', sa.JSON(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_servers_category', 'mcp_servers', ['category'], unique=False)
    op.create_index('idx_mcp_servers_status', 'mcp_servers', ['status'], unique=False)
    op.create_index('idx_mcp_servers_tenant_slug', 'mcp_servers', ['tenant_id', 'slug'], unique=True)
    op.create_index(op.f('ix_mcp_servers_status'), 'mcp_servers', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_servers_tenant_id'), 'mcp_servers', ['tenant_id'], unique=False)
    op.create_table('mcp_server_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_overrides', sa.JSON(), nullable=True),
    sa.Column('env_overrides', sa.JSON(), nullable=True),
    sa.Column('allowed_tools', sa.JSON(), nullable=True),
    sa.Column('denied_tools', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_configs_agent', 'mcp_server_configs', ['agent_id'], unique=False)
    op.create_index('idx_mcp_configs_tenant_server', 'mcp_server_configs', ['tenant_id', 'server_id'], unique=False)
    op.create_index(op.f('ix_mcp_server_configs_agent_id'), 'mcp_server_configs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_mcp_server_configs_server_id'), 'mcp_server_configs', ['server_id'], unique=False)
    op.create_index(op.f('ix_mcp_server_configs_tenant_id'), 'mcp_server_configs', ['tenant_id'], unique=False)
    op.create_table('mcp_tool_executions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_output', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('server_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('is_retry', sa.Boolean(), nullable=False),
    sa.Column('parent_execution_id', sa.UUID(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_executions_started_at', 'mcp_tool_executions', ['started_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_mcp_executions_status', 'mcp_tool_executions', ['status'], unique=False)
    op.create_index('idx_mcp_executions_tenant_server', 'mcp_tool_executions', ['tenant_id', 'server_id'], unique=False)
    op.create_index('idx_mcp_executions_tool', 'mcp_tool_executions', ['tool_name'], unique=False)
    op.create_index(op.f('ix_mcp_tool_executions_agent_id'), 'mcp_tool_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_mcp_tool_executions_conversation_id'), 'mcp_tool_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_mcp_tool_executions_message_id'), 'mcp_tool_executions', ['message_id'], unique=False)
    op.create_index(op.f('ix_mcp_tool_executions_server_id'), 'mcp_tool_executions', ['server_id'], unique=False)
    op.create_index(op.f('ix_mcp_tool_executions_started_at'), 'mcp_tool_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_mcp_tool_executions_status'), 'mcp_tool_executions', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_tool_executions_tenant_id'), 'mcp_tool_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mcp_tool_executions_tool_name'), 'mcp_tool_executions', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_tool_executions_tool_name'), table_name='mcp_tool_executions')
    op.drop_index(op.f('ix_mcp_tool_executions_tenant_id'), table_name='mcp_tool_executions')
    op.drop_index(op.f('ix_mcp_tool_executions_status'), table_name='mcp_tool_executions')
    op.drop_index(op.f('ix_mcp_tool_executions_started_at'), table_name='mcp_tool_executions')
    op.drop_index(op.f('ix_mcp_tool_executions_server_id'), table_name='mcp_tool_executions')
    op.drop_index(op.f('ix_mcp_tool_executions_message_id'), table_name='mcp_tool_executions')
    op.drop_index(op.f('ix_mcp_tool_executions_conversation_id'), table_name='mcp_tool_executions')
    op.drop_index(op.f('ix_mcp_tool_executions_agent_id'), table_name='mcp_tool_executions')
    op.drop_index('idx_mcp_executions_tool', table_name='mcp_tool_executions')
    op.drop_index('idx_mcp_executions_tenant_server', table_name='mcp_tool_executions')
    op.drop_index('idx_mcp_executions_status', table_name='mcp_tool_executions')
    op.drop_index('idx_mcp_executions_started_at', table_name='mcp_tool_executions', postgresql_using='btree')
    op.drop_table('mcp_tool_executions')
    op.drop_index(op.f('ix_mcp_server_configs_tenant_id'), table_name='mcp_server_configs')
    op.drop_index(op.f('ix_mcp_server_configs_server_id'), table_name='mcp_server_configs')
    op.drop_index(op.f('ix_mcp_server_configs_agent_id'), table_name='mcp_server_configs')
    op.drop_index('idx_mcp_configs_tenant_server', table_name='mcp_server_configs')
    op.drop_index('idx_mcp_configs_agent', table_name='mcp_server_configs')
    op.drop_table('mcp_server_configs')
    op.drop_index(op.f('ix_mcp_servers_tenant_id'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_status'), table_name='mcp_servers')
    op.drop_index('idx_mcp_servers_tenant_slug', table_name='mcp_servers')
    op.drop_index('idx_mcp_servers_status', table_name='mcp_servers')
    op.drop_index('idx_mcp_servers_category', table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_mcp_server_registry_status'), table_name='mcp_server_registry')
    op.drop_index(op.f('ix_mcp_server_registry_slug'), table_name='mcp_server_registry')
    op.drop_index(op.f('ix_mcp_server_registry_name'), table_name='mcp_server_registry')
    op.drop_index(op.f('ix_mcp_server_registry_category'), table_name='mcp_server_registry')
    op.drop_index('idx_registry_status', table_name='mcp_server_registry')
    op.drop_index('idx_registry_featured', table_name='mcp_server_registry')
    op.drop_index('idx_registry_category', table_name='mcp_server_registry')
    op.drop_table('mcp_server_registry')
    # ### end Alembic commands ###
