"""Add workflow and multi-agent orchestration models

Revision ID: ecc4af4f162e
Revises: 71c3dad7290a
Create Date: 2025-11-21 23:49:15.755278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc4af4f162e'
down_revision: Union[str, None] = '71c3dad7290a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_strategy', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflows_category', 'workflows', ['category'], unique=False)
    op.create_index('idx_workflows_status', 'workflows', ['status'], unique=False)
    op.create_index('idx_workflows_tenant_slug', 'workflows', ['tenant_id', 'slug'], unique=True)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_step', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_executions_started_at', 'workflow_executions', ['started_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_workflow_executions_status', 'workflow_executions', ['status'], unique=False)
    op.create_index('idx_workflow_executions_tenant_workflow', 'workflow_executions', ['tenant_id', 'workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_started_at'), 'workflow_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_tenant_id'), 'workflow_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('from_agent_id', sa.UUID(), nullable=False),
    sa.Column('to_agent_id', sa.UUID(), nullable=True),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('requires_response', sa.Boolean(), nullable=False),
    sa.Column('in_response_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['in_response_to'], ['agent_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_messages_from_agent', 'agent_messages', ['from_agent_id'], unique=False)
    op.create_index('idx_agent_messages_sent_at', 'agent_messages', ['sent_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_agent_messages_to_agent', 'agent_messages', ['to_agent_id'], unique=False)
    op.create_index('idx_agent_messages_type', 'agent_messages', ['message_type'], unique=False)
    op.create_index('idx_agent_messages_workflow', 'agent_messages', ['workflow_execution_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_from_agent_id'), 'agent_messages', ['from_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_message_type'), 'agent_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_agent_messages_sent_at'), 'agent_messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_status'), 'agent_messages', ['status'], unique=False)
    op.create_index(op.f('ix_agent_messages_tenant_id'), 'agent_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_to_agent_id'), 'agent_messages', ['to_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_workflow_execution_id'), 'agent_messages', ['workflow_execution_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_tasks_agent_status', 'agent_tasks', ['agent_id', 'status'], unique=False)
    op.create_index('idx_agent_tasks_due_at', 'agent_tasks', ['due_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_agent_tasks_priority', 'agent_tasks', ['priority'], unique=False)
    op.create_index('idx_agent_tasks_workflow', 'agent_tasks', ['workflow_execution_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_agent_id'), 'agent_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_created_at'), 'agent_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_tenant_id'), 'agent_tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_workflow_execution_id'), 'agent_tasks', ['workflow_execution_id'], unique=False)
    op.create_table('workflow_step_executions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step_executions_agent', 'workflow_step_executions', ['agent_id'], unique=False)
    op.create_index('idx_step_executions_status', 'workflow_step_executions', ['status'], unique=False)
    op.create_index('idx_step_executions_workflow', 'workflow_step_executions', ['workflow_execution_id', 'step_index'], unique=False)
    op.create_index(op.f('ix_workflow_step_executions_agent_id'), 'workflow_step_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_workflow_step_executions_conversation_id'), 'workflow_step_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_workflow_step_executions_started_at'), 'workflow_step_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_step_executions_status'), 'workflow_step_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_step_executions_tenant_id'), 'workflow_step_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_step_executions_workflow_execution_id'), 'workflow_step_executions', ['workflow_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_step_executions_workflow_execution_id'), table_name='workflow_step_executions')
    op.drop_index(op.f('ix_workflow_step_executions_tenant_id'), table_name='workflow_step_executions')
    op.drop_index(op.f('ix_workflow_step_executions_status'), table_name='workflow_step_executions')
    op.drop_index(op.f('ix_workflow_step_executions_started_at'), table_name='workflow_step_executions')
    op.drop_index(op.f('ix_workflow_step_executions_conversation_id'), table_name='workflow_step_executions')
    op.drop_index(op.f('ix_workflow_step_executions_agent_id'), table_name='workflow_step_executions')
    op.drop_index('idx_step_executions_workflow', table_name='workflow_step_executions')
    op.drop_index('idx_step_executions_status', table_name='workflow_step_executions')
    op.drop_index('idx_step_executions_agent', table_name='workflow_step_executions')
    op.drop_table('workflow_step_executions')
    op.drop_index(op.f('ix_agent_tasks_workflow_execution_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_tenant_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_created_at'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent_id'), table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_workflow', table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_priority', table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_due_at', table_name='agent_tasks', postgresql_using='btree')
    op.drop_index('idx_agent_tasks_agent_status', table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_agent_messages_workflow_execution_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_to_agent_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_tenant_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_status'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_sent_at'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_message_type'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_from_agent_id'), table_name='agent_messages')
    op.drop_index('idx_agent_messages_workflow', table_name='agent_messages')
    op.drop_index('idx_agent_messages_type', table_name='agent_messages')
    op.drop_index('idx_agent_messages_to_agent', table_name='agent_messages')
    op.drop_index('idx_agent_messages_sent_at', table_name='agent_messages', postgresql_using='btree')
    op.drop_index('idx_agent_messages_from_agent', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_tenant_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_started_at'), table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_tenant_workflow', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_status', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_started_at', table_name='workflow_executions', postgresql_using='btree')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index('idx_workflows_tenant_slug', table_name='workflows')
    op.drop_index('idx_workflows_status', table_name='workflows')
    op.drop_index('idx_workflows_category', table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
